swagger: '2.0'
info:
  title: API V1
  version: v1
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /users:
    post:
      summary: Create an user
      tags:
        - Users
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: user
          in: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              password_confirmation:
                type: string
              role:
                type: string
              phonenumber:
                type: string
            required:
              - email
              - password
              - password_confirmation
      responses:
        '200':
          description: user created
  /api/v1/auth:
    post:
      summary: User SignIn
      tags:
        - Users
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: user
          in: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            required:
              - email
              - password
      responses:
        '200':
          description: SignedIn


  /organizations:
    get:
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
      summary: Show list of organizations
      tags:
        - Organizations
      consumes:
        - application/json
        - application/xml
      responses:
        '200':
          description: ok
    post:
      summary: Create an organization
      tags:
        - Organizations
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: organization
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
            required:
              - name
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
      responses:
        '200':
          description: organization created
    put:
      summary: Update an organization
      tags:
        - Organizations
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: organization
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
            required:
              - name
      responses:
        '200':
          description: organization updated


  /organizations/{organization_id}:
    get:
      summary: Show organizations
      tags:
        - Organizations
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: organization_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: OK
    delete:
      summary: Delete an organization
      tags:
        - Organizations
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: organization_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: organization deleted
  /organizations/register-as-admin:
    post:
      summary: Register an user as admin in an organization
      tags:
        - Organizations
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: current_user
          in: body
          schema:
            type: object
            properties:
              current_user:
                type: string
              organization_id:
                type: integer
            required:
              - current_user
              - organization_id
      responses:
        '200':
          description: OK

  /addressbooks:
    get:
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
      summary: Show list of contacts in addressbooks
      tags:
        - Addressbook
      consumes:
        - application/json
        - application/xml
      responses:
        '200':
          description: ok
    post:
      summary: Create an contact in addressbook
      tags:
        - Addressbook
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: organization
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              phone:
                type: string
              organization:
                type: object
            required:
              - name
              - phone
      responses:
        '200':
          description: contact created
    put:
      summary: Update an contact in addressbook
      tags:
        - Addressbook
      consumes:
        - application/json
        - application/xml
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: organization
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              phone:
                type: string
            required:
              - name
              - phone
      responses:
        '200':
          description: contact updated
  /addressbooks/list-organization-contacts/{id}:
    get:
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: id
          in: path
          required: true
          type: integer
      summary: Show list organization contact list
      tags:
        - Addressbook
      consumes:
        - application/json
        - application/xml
      responses:
        '200':
          description: ok
  /addressbooks/search-contact-by-name/{organization_id}/{name}:
    get:
      parameters:
        - name: Authorization
          description: an authorization header
          required: true
          type: string
          in: header
        - name: organization_id
          in: path
          required: true
          type: integer
        - name: name
          in: path
          required: true
          type: integer
      summary: Find an especific contact
      tags:
        - Addressbook
      consumes:
        - application/json
        - application/xml
      responses:
        '200':
          description: ok